### ISSUE TITLE
Create shared lib

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/blob#1]
Implements partially
https://github.com/OpusCapita/businessnetwork/issues/19

Create blob-access shared lib and implement basic functionality as outlined in spec
https://docs.google.com/document/d/17OsivCVNJCW6NUp5OFcbJDfEwJdCXUWY0sjyikiQGcM/edit#

List
Get
Create
Update
Delete

**Comment by kwierchris** [comment]
https://github.com/OpusCapita/blob-client
