### ISSUE TITLE
doc with link to legacy GitHub Orga

### ISSUE THREAD

**Issue by RDeau** [OpusCapita/blob#11]
minor thing but I saw that in a few places in this file at least

https://github.com/OpusCapita/blob/blob/ba495e65c31fa50631be018aab19940772f62ad4/src/server/db/migrations/3-blob.test.js#L15

Could I just fix issue like that by myself or better to create an issue or post a message on slack?

**Comment by kwierchris** [comment]
Fixed by removal ;)
