### ISSUE TITLE
Directory list does not include subdirectories

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/blob#16]
The GET for a dir correctly includes files in the response, but directories are not covered.

**Comment by kwierchris** [comment]
Try query parameter **recursive** set to true. Otherwise it was said that there are no directories in azure so they are not covered in file lists

**Comment by gr4per** [comment]
https://stage.businessnetwork.opuscapita.com/blob/api/opuscapita/files/public/docs/einvoice-send/?recursive=true
result: []

whereas
https://stage.businessnetwork.opuscapita.com/blob/api/opuscapita/files/public/docs/einvoice-send/pdf/

result: [{"name":"OpusCapitaTermsAndConditions.html","extension":".html","location":"/public/docs/einvoice-send/pdf","path":"/public/docs/einvoice-send/pdf/OpusCapitaTermsAndConditions.html","size":2684,"isFile":true,"isDirectory":false,"lastModified":"2017-10-10T16:57:08.000Z","contentType":"text/plain","checksum":"azUkiHfiMk9f6t05VmhDCw=="},{"name":"OpusCapitaTermsAndConditions_de.html","extension":".html","location":"/public/docs/einvoice-send/pdf","path":"/public/docs/einvoice-send/pdf/OpusCapitaTermsAndConditions_de.html","size":3286,"isFile":true,"isDirectory":false,"lastModified":"2017-10-10T16:57:08.000Z","contentType":"text/plain","checksum":"4Z2rKNnTvBczYx5JHmFKBw=="}]


Von: Christian Drengenberg [mailto:notifications@github.com]
Gesendet: Montag, 27. November 2017 12:35
An: OpusCapita/blob <blob@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Assign <assign@noreply.github.com>
Betreff: Re: [OpusCapita/blob] Directory list does not include subdirectories (#16)


Try query parameter recursive set to true. Otherwise it was said that there are no directories in azure so they are not covered in file lists
