### ISSUE TITLE
Calling GET on api/files/?recursive=true returns empty array

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/blob#18]
Expect to get public and private folders back, but there is nothing.

**Comment by kwierchris** [comment]
It should return {"message":"The provided path is invalid. Has to start with either /private or /public."}. It has been defined, that there should only be public and private directories so blob checks this and restricts the valid path to these two options. They are not dynamic at all so the question is, if we should really list these two as directories.

**Comment by gr4per** [comment]
Yes for writing it makes sense.
But for listing dirs the root / path obviously has to return the directories public and private as subfolders...



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Christian Drengenberg <notifications@github.com>
Datum: 05.12.17 10:54 (GMT+01:00)
An: OpusCapita/blob <blob@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>, Author <author@noreply.github.com>
Betreff: Re: [OpusCapita/blob] Calling GET on api/files/?recursive=true returns empty array (#18)


It should return {"message":"The provided path is invalid. Has to start with either /private or /public."}. It has been defined, that there should only be public and private directories so blob checks this and restricts the valid path to these two options. They are not dynamic at all so the question is, if we should really list these two as directories.

**Comment by kwierchris** [comment]
But then people might think that they could create additional directories there which they can't.

**Comment by gr4per** [comment]
If they read the docs or error message I don’t expect this to be a problem.

Von: Christian Drengenberg [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Dezember 2017 11:24
An: OpusCapita/blob <blob@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Author <author@noreply.github.com>
Betreff: Re: [OpusCapita/blob] Calling GET on api/files/?recursive=true returns empty array (#18)


But then people might think that they could create additional directories there which they can't.
