### ISSUE TITLE
Add super-role to manage any tenant' files

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/blob#8]
There is a need of role that could be assigned to some service-users (f.e. svc_invoice) to manipulate any tenant's files without request-populated user-data.

**Comment by gr4per** [comment]
I propose to do permissions per service subtree, so we can give invoice service (svc_invoice role) the permission to blob/private/invoice (create, delete)

**Comment by dzhitomirsky-sc** [comment]
@gr4per @kwierchris We strongly need this feature for Paris presentation. Do you have any estimations when it could be done.

**Comment by kwierchris** [comment]
For the actual presentation you may want to use a user with the *admin* role assigned. Admins have full access.

**Comment by kwierchris** [comment]
Blob is now supporting our xroles feature. https://github.com/OpusCapita/user/blob/develop/usecases/UserRoleTenantAssignement.md
Better permission management should follow in the future.
