### ISSUE TITLE
Support of tenant independent files

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/blob#9]
We need to provide global (not tenant specific) possibility to provide e.g. documentation - see OpusCapita/onboarding/issues/315

Proposal path:
  public/bnp/docs/

**Comment by kwierchris** [comment]
What about making it from -> to
* /api/:tenantId/files/:path -> /api/files/:path
* /public/api/:tenantId/files/:path -> /public/api/files/:path

and then internally map it to a fixed azure container including **public** and **private** where private can only be accessed with a valid user session in blob.

**Comment by gr4per** [comment]
actually any non customer specific files can go in the service source, e.g. onboarding/static/your/file/name
Storing them on blob has no benefit I believe.

**Comment by kwierchris** [comment]
After some discussion I will add a tenant opuscapita to blob and its migrations so it will always be available. For now we can only access public paths there.
